name: Github-action-demo
'on':
  push:
    branches:
      - CR-123-autotest-1668511891254
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push the Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: >
          export VERSION=$(cat service.yaml)

          export CF_IMAGE=$DOCKERHUB_USERNAME/${{ github.event.repository.name
          }}:$VERSION

          echo "CF_IMAGE=$CF_IMAGE" >> $GITHUB_ENV

          docker build . --file Dockerfile --build-arg COLOR=$VERSION --tag
          $CF_IMAGE && docker push $CF_IMAGE
      - name: report image
        with:
          CF_API_KEY: ${{secrets.CF_IL_API_KEY}}
          CF_RUNTIME_NAME: codefresh-hosted
          CF_IMAGE: ${{env.CF_IMAGE}}
          CF_CONTAINER_REGISTRY_INTEGRATION: dockerhub-test
          CF_GIT_BRANCH: CR-123-autotest-1668511891254
          CF_ISSUE_TRACKING_INTEGRATION: jira-test
          CF_JIRA_PROJECT_PREFIX: CR
          CF_JIRA_MESSAGE: Jira message
          CF_GITHUB_TOKEN: ${{secrets.PAT}}
        uses: codefresh-io/codefresh-report-image@latest
      - name: Checkout csdp-salesdemo_applications
        uses: actions/checkout@v3
        with:
          repository: testcodefresh/canary-rollout
          path: .
      - name: Update application version
        run: >
          IMAGE=${{ env.CF_IMAGE }} yq -i
          '.spec.template.spec.containers.[0].image = strenv(IMAGE)'
          canary-rollout.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-application-version
          delete-branch: true
          title: Update application version
          body: |
            Update deployment version
            - Updated new version for hello-world application
          labels: |
            automated pr
          draft: false
